const categoriesObj = [
  {
    key: '1',
    title: "Men's Shirt",
    sectiontitle: 'Shirt',
    icon: require('../assets/icons/men-shirt.png'),
    type: 'men',
    shortcut: true,
  },
  {
    key: '2',
    title: "Men's Accessories",
    sectiontitle: 'Accessories',
    icon: require('../assets/icons/men-bag.png'),
    type: 'men',
    shortcut: true,
  },
  {
    key: '3',
    title: 'T-shirt',
    sectiontitle: 'T-shirt',
    icon: require('../assets/icons/t-shirt.png'),
    type: 'men',
    shortcut: true,
  },
  {
    key: '4',
    title: "Men's Shoes",
    sectiontitle: 'Shoes',
    icon: require('../assets/icons/men-shoes.png'),
    type: 'men',
    shortcut: true,
  },
  {
    key: '5',
    title: "Men's Pants",
    sectiontitle: 'Pants',
    icon: require('../assets/icons/men-pants.png'),
    type: 'men',
    shortcut: true,
  },

  {
    key: '6',
    title: "Men's Underwear",
    sectiontitle: 'Underwear',
    icon: require('../assets/icons/men-underwear.png'),
    type: 'men',
    shortcut: false,
  },
  {
    key: '7',
    title: 'Dresses',
    sectiontitle: 'Dresses',
    icon: require('../assets/icons/dress.png'),
    type: 'women',
    shortcut: true,
  },

  {
    key: '8',
    title: "Women's Shirt",
    sectiontitle: 'Shirt',
    icon: require('../assets/icons/men-shirt.png'),
    type: 'men',
    shortcut: true,
  },
  {
    key: '9',
    title: "Women's Pants",
    sectiontitle: 'Pants',
    icon: require('../assets/icons/women-pants.png'),
    type: 'women',
    shortcut: true,
  },
  {
    key: '10',
    title: 'Skirt',
    sectiontitle: 'Skirt',
    icon: require('../assets/icons/skirt.png'),
    type: 'women',
    shortcut: true,
  },
  {
    key: '11',
    title: "Women's Accessories",
    sectiontitle: 'Accessories',
    icon: require('../assets/icons/women-bag.png'),
    type: 'women',
    shortcut: true,
  },
  {
    key: '12',
    title: "Women's Shoes",
    sectiontitle: 'Shoes',
    icon: require('../assets/icons/women-shoes.png'),
    type: 'women',
    shortcut: true,
  },
  {
    key: '13',
    title: 'Women"s T-shirt',
    sectiontitle: 'T-shirt',
    icon: require('../assets/icons/women-tshirt.png'),
    type: 'women',
    shortcut: false,
  },
  {
    key: '14',
    title: 'Bikini',
    sectiontitle: 'Bikini',
    icon: require('../assets/icons/bikini.png'),
    type: 'women',
    shortcut: false,
  },
];

export const shortcutCateegories = [
  {
    key: '1',
    title: "Men's Shirt",
    sectiontitle: 'Shirt',
    icon: require('../assets/icons/men-shirt.png'),
    type: 'men',
    shortcut: true,
  },
  {
    key: '2',
    title: "Men's Accessories",
    sectiontitle: 'Accessories',
    icon: require('../assets/icons/men-bag.png'),
    type: 'men',
    shortcut: true,
  },
  {
    key: '3',
    title: 'T-shirt',
    sectiontitle: 'T-shirt',
    icon: require('../assets/icons/t-shirt.png'),
    type: 'men',
    shortcut: true,
  },
  {
    key: '4',
    title: "Men's Shoes",
    sectiontitle: 'Shoes',
    icon: require('../assets/icons/men-shoes.png'),
    type: 'men',
    shortcut: true,
  },
  {
    key: '5',
    title: "Men's Pants",
    sectiontitle: 'Pants',
    icon: require('../assets/icons/men-pants.png'),
    type: 'men',
    shortcut: true,
  },

  {
    key: '7',
    title: 'Dresses',
    sectiontitle: 'Dresses',
    icon: require('../assets/icons/dress.png'),
    type: 'women',
    shortcut: true,
  },

  {
    key: '8',
    title: "Women's Shirt",
    sectiontitle: 'Shirt',
    icon: require('../assets/icons/men-shirt.png'),
    type: 'men',
    shortcut: true,
  },
  {
    key: '9',
    title: "Women's Pants",
    sectiontitle: 'Pants',
    icon: require('../assets/icons/women-pants.png'),
    type: 'women',
    shortcut: true,
  },
  {
    key: '10',
    title: 'Skirt',
    sectiontitle: 'Skirt',
    icon: require('../assets/icons/skirt.png'),
    type: 'women',
    shortcut: true,
  },
  {
    key: '11',
    title: "Women's Accessories",
    sectiontitle: 'Accessories',
    icon: require('../assets/icons/women-bag.png'),
    type: 'women',
    shortcut: true,
  },
  {
    key: '12',
    title: "Women's Shoes",
    sectiontitle: 'Shoes',
    icon: require('../assets/icons/women-shoes.png'),
    type: 'women',
    shortcut: true,
  },
];

export default categoriesObj;
