export const flashSale = [
  {
    key: '1',
    image: require('../assets/images/products/fs-nike.png'),
    title: 'FS - Nike Air Max 270 React ENG',
    price: 229.43,
    prevPrice: 543.33,
    off: 24,
    discount: true,
  },
  {
    key: '2',
    image: require('../assets/images/products/quilted-maxi-bag.png'),
    title: 'FS - QUILTED MAXI CROSS BAG',
    price: 229.43,
    prevPrice: 543.33,
    off: 24,
    discount: true,
  },
  {
    key: '3',
    image: require('../assets/images/products/fs-nike-max270.png'),
    title: 'FS - Nike Air Max 270 React ENG',
    price: 229.43,
    prevPrice: 543.33,
    off: 24,
    discount: true,
  },
  {
    key: '4',
    image: require('../assets/images/products/fs-nike.png'),
    title: 'FS - Nike Air Max 270 React ENG',
    price: 229.43,
    prevPrice: 543.33,
    off: 24,
    discount: true,
  },
  {
    key: '5',
    image: require('../assets/images/products/quilted-maxi-bag.png'),
    title: 'FS - QUILTED MAXI CROSS BAG',
    price: 229.43,
    prevPrice: 543.33,
    off: 24,
    discount: true,
  },
  {
    key: '7',
    image: require('../assets/images/products/fs-nike-max270.png'),
    title: 'FS - Nike Air Max 270 React ENG',
    price: 229.43,
    prevPrice: 543.33,
    off: 24,
    discount: true,
  },
];

export const megaSale = [
  {
    key: '1',
    image: require('../assets/images/products/fs-nike.png'),
    title: 'MS - Nike Air Max 270 React ENG',
    price: 229.43,
    prevPrice: 543.33,
    off: 24,
    discount: true,
  },
  {
    key: '2',
    image: require('../assets/images/products/quilted-maxi-bag.png'),
    title: 'MS - QUILTED MAXI CROSS BAG',
    price: 229.43,
    prevPrice: 543.33,
    off: 24,
    discount: true,
  },
  {
    key: '3',
    image: require('../assets/images/products/fs-nike-max270.png'),
    title: 'MS - Nike Air Max 270 React ENG',
    price: 229.43,
    prevPrice: 543.33,
    off: 24,
    discount: true,
  },
  {
    key: '4',
    image: require('../assets/images/products/fs-nike.png'),
    title: 'MS - Nike Air Max 270 React ENG',
    price: 229.43,
    prevPrice: 543.33,
    off: 24,
    discount: true,
  },
  {
    key: '5',
    image: require('../assets/images/products/quilted-maxi-bag.png'),
    title: 'MS - QUILTED MAXI CROSS BAG',
    price: 229.43,
    prevPrice: 543.33,
    off: 24,
    discount: true,
  },
  {
    key: '7',
    image: require('../assets/images/products/fs-nike-max270.png'),
    title: 'MS - Nike Air Max 270 React ENG',
    price: 229.43,
    prevPrice: 543.33,
    off: 24,
    discount: true,
  },
];

export const products = [
  {
    key: '1',
    rating: 4,
    image: require('../assets/images/products/fs-nike.png'),
    title: 'Nike Air Max 270 React ENG',
    price: 229.43,
    prevPrice: 543.33,
    off: 24,
    discount: true,
  },
  {
    key: '2',
    rating: 4,
    image: require('../assets/images/products/quilted-maxi-bag.png'),
    title: 'QUILTED MAXI CROSS BAG',
    price: 229.43,
    prevPrice: 543.33,
    off: 24,
    discount: true,
  },
  {
    key: '5',
    rating: 3,
    image: require('../assets/images/products/nike--.png'),
    title: 'Nike Air Max 270 React ENG',
    price: 229.43,
    prevPrice: 543.33,
    off: 24,
    discount: true,
  },
  {
    key: '3',
    rating: 3,
    image: require('../assets/images/products/fs-nike-max270.png'),
    title: 'Nike Air Max 270 React ENG',
    price: 229.43,
    prevPrice: 543.33,
    off: 24,
    discount: true,
  },
  {
    key: '4',
    rating: 5,
    image: require('../assets/images/products/purse-3.png'),
    title: '3 Women"s Bag set ',
    price: 229.43,
    prevPrice: 543.33,
    off: 24,
    discount: true,
  },
  {
    key: '6',
    rating: 3,
    image: require('../assets/images/products/nike-.png'),
    title: 'Nike Air Max 270 React ENG',
    price: 229.43,
    prevPrice: 543.33,
    off: 24,
    discount: true,
  },
];
